### ISSUE TITLE
special character support

### ISSUE THREAD

**Issue by Haroenv** [bullgit/blah-code#2]
idea by @dervondenbergen: encode the unicode codepoint: `a` (61) become `blah blah blah blah blah blah, blah;`

**Comment by dervondenbergen** [comment]
After some thinking, this is actually possible, as the space has also a unicode codepoint, and there fore the `blah`s can be after each other, although a next word starts.

**Comment by radiovisual** [comment]
+1

**Comment by radiovisual** [comment]
Using the idea presented by @Haroenv is a good one, but using this method would still require a lot of "blahs" to be printed if you want to support large unicode values. 

For example, the character `ẞ` has a really high decimal value of `7838`, using @Haroenv's method above, this would mean we would have to print 26 blahs to represent a large number like `7838`

```
<7 blahs><comma> <8 blahs><comma> <3 blahs><comma> <8 blahs><semicolon> = 26 blahs = 7838

blah blah blah blah blah blah blah, blah blah blah blah blah blah blah blah, blah blah blah, blah blah blah blah blah blah blah blah; // === 7838
```

So, in order to support ANY unicode value, and minimize the output of the output string, you could save yourself even more room by hiding the encoded values into each 'blah', for example, if you think of your encoding system to be like a [sorban](https://en.wikipedia.org/wiki/Soroban), then you know you will never need more than 9 'a''s in each "blah", so a large value of `7838` could look like this:

```
blaaaaaaaah blaaaaaaaaah blaaaah blaaaaaaaaah. = 7838
```

The period, or any punctuation at all (you could cycle through them at random) denotes the end of a character. This system would need a 0-index notation to account for Zero, so `blah === 0, blaah === 1, etc`

If you wanted to keep the `blah`'s even shorter, then you can think about introducing another "blah"-like word into the output, which can signal a "add 3" directive. For example, if the word "blee" acted like a prefix incriminator to direct some the "a"'s in the following "blah"'s to increase in value, then you can treat the "e"'s in "blee" as a mask. So the rule could be "Take the number of e's in 'blee' and use those to increment the same number of 'a''s in the following "blah" by 3, the remaining "a"'s count as 1", so you can get to super high values like 7838 like this:

```
blee blaaah blaaaah ble blah blee blaaaah. // === 7838
```

Which is still shorter (less characters) than the direct encoding above, even though they both represent the same values:

``` js
// both systems equal 7838
blaaaaaaaah blaaaaaaaaah blaaaah blaaaaaaaaah.
blee blaaah blaaaah ble blah blee blaaaah.             
```

...and the "blee blah blah" adds a little more character to the output --- makes it feel more randomized and playful.

Anyway, this is just my `ble blaaah` (2) cents. Free hamburgers! --> :hamburger: :hamburger: :hamburger:

**Comment by Haroenv** [comment]
This is also similar to what I suggested, a combination of BSD encoding. (7 blahs, 8 blahs, 3 blahs, 8 blahs.). The "3" keyword "bleh" is also an interesting idea.

**Comment by dervondenbergen** [comment]
@radiovisual this is very much knowledge in little space :+1: :100:

**Comment by radiovisual** [comment]
Yeah, @Haroenv yours was a good idea. I just thought to "code golf" it, and expand on the ideas to support really large values with minimal output.

When you compare the three systems we have introduced so far, some are more verbose then others, even though they represent the same value of `7838`:

**Option 1** (133 chars)

```
blah blah blah blah blah blah blah, blah blah blah blah blah blah blah blah, blah blah blah, blah blah blah blah blah blah blah blah;
```

**Option 2** (46 chars)

```
blaaaaaaaah blaaaaaaaaah blaaaah blaaaaaaaaah.
```

**Option 3** (42 chars)

```
blee blaaah blaaaah ble blah blee blaaaah.
```

**Comment by mischah** [comment]
F**k me 😳

@radiovisual Thanks for dropping mad science into this issue. :ok_hand: 

Gotta twist my head around this in my spare time.

**Comment by radiovisual** [comment]
@Haroenv , I amended my long post to account for my original misunderstanding of your idea. I originally thought your idea meant printing 791 "blahs" to account for a large value like 7838, but instead, you and I were on the same page with only needing 26: `(7 blahs, 8 blahs, 3 blahs, 8 blahs.)`, so I edited my post to reflect that. Sorry about the confusion.

**Comment by Haroenv** [comment]
I made this draft executing what I think you wanted:

``` js
var blahs = ['bleh','blah','blih','blaah','bla','blu','ble','blaaa','blahh','blee'];

var encode = function(text) {
  var blah = [];
  for (var letter in text) {
    var encoded = []
    var temporary = text[letter].charCodeAt(0).toString().split('');
    for (var code in temporary) {
      encoded.push(blahs[temporary[code]]);
    }
    blah.push(encoded.join(' '));
  }
  return blah.join('. ');
}

var decode = function(text) {
  var output = [];
  var encoded = text.split('. ');
  for (var char in encoded) {
    var codes = encoded[char].split(' ');
    var character = [];
    for (var i in codes) {
      character.push(blahs.indexOf(codes[i]));
    }
    output.push(String.fromCharCode(character.join('')));
  }
  return output.join('');
}

var encoded = encode('meme 👌');
console.log(encoded);
var decoded = decode(encoded);
console.log(decoded);
```

in the console this shows: 

```
blah bleh blee. blah bleh blah. blah bleh blee. blah bleh blah. blaah blih. blu blu blaah blu blaaa. blu ble blaah blee ble
```

and 

```
meme 👌
```

**Comment by dervondenbergen** [comment]
:+1:

**Comment by radiovisual** [comment]
@Haroenv , nice work! Your code actually takes a different approach to what I had proposed, but your idea is better, because it results in even shorter output. Your new idea is to have 10 different "blah" variations, where each unique "blah" equals a value from `0 - 9`, and those get strung together to create large numerical values. Nice work!

Here is a demonstration of how your new idea has even shorter output than my best idea, I will use your example of `meme 👌`, which results in the character codes of `[109, 101, 109, 101, 32, 55357]`

**Option 1** (10 unique 'blahs') 
`meme 👌` === 123 characters

```
blah bleh blee. blah bleh blah. blah bleh blee. blah bleh blah. blaah blih. blu blu blaah blu blaaa. blu ble blaah blee ble
```

**Option 2** ('blee' increment masking)
`meme 👌` === 139 characters

```
blaah blah bleee blaaah, blaah blah blaah, blaah blah bleee blaaah, blaah blah blaah; blaaaah blaaah; ble blaaah blaaah blah blaaa blaaaaa;
```

So I vote for @Haroenv's  "10 unique blahs" approach to creating large numerical representations.

:+1:

**Comment by mischah** [comment]
:+1:

I love it. 

@Haroenv PR?

**Comment by Haroenv** [comment]
so @mischah how do we plan doing that with several versions? I guess the `apeCode` will still use the old method for now, and we just a new array to use the new method and bump the version number to a breaking change?

**Comment by radiovisual** [comment]
Couldn't the same idea be applied to your `apeCode`? Just have 10 different "monkey sounds' using the same ideas. Then you can share the same code base, and just switch out the "blahs" with "monkey sounds" depending on the API the user wants:

``` js
var blahs = ['bleh','blah','blih','blaah','bla','blu','ble','blaaa','blahh','blee'];
var ooks = ['Ook', 'Oook', 'Ooook', 'Oooook', 'Ook!', 'Oook?', 'Oook.', 'Oook!?'];
```

that way you have less code to maintain, but suddenly your apeCode can share the same benefit of being able to handle special characters...

**Comment by Haroenv** [comment]
Thats an interesting idea @radiovisual, what do you think @hardcoded-dev (original author of `apeCode`)? I think it could be implemented, and the functions could have maybe an extra parameter that said what kind of encoding is used (default `blahs`).

**Comment by mischah** [comment]
I refactored ape code to make use of the new stuff. 

The language defaults to `languages.blah`. So you can still use:

```
blahCode.encode('Hi there! What’s up?')
```

If you like to use the ape language you can pass an additional param:

```
blahCode.encode('Hi there!', 'ooks')
```

Just have to update the readme.

cc/ @hardcoded-dev

**Comment by radiovisual** [comment]
Wow, the new changes seriously cleaned up the new codebase. Nice work @Haroenv and @mischah  :+1: 

Now we can start having fun encoding messages like: :hamburger: + :beer: === :hankey: !

**Comment by mischah** [comment]
Yeah 🦄
